
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/iRU/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/iRU/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/iRU/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/iRU/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.27.29111 для x64
      (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
      
      CMakeCCompilerId.c
      Microsoft (R) Incremental Linker Version 14.27.29111.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCCompilerId.exe 
      CMakeCCompilerId.obj 
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/iRU/Documents/GitHub/YADRO-task/cmake-build-debug-visual-studio/CMakeFiles/3.28.1/CompilerIdC/CMakeCCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/iRU/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1182 (message)"
      - "C:/Users/iRU/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:247 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Users/iRU/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        main.c
        Примечание: включение файла:  C:\\Users\\iRU\\Documents\\GitHub\\YADRO-task\\cmake-build-debug-visual-studio\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Примечание: включение файла:  "
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/iRU/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/iRU/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/iRU/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.27.29111 для x64
      (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
      
      CMakeCXXCompilerId.cpp
      Microsoft (R) Incremental Linker Version 14.27.29111.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCXXCompilerId.exe 
      CMakeCXXCompilerId.obj 
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/iRU/Documents/GitHub/YADRO-task/cmake-build-debug-visual-studio/CMakeFiles/3.28.1/CompilerIdCXX/CMakeCXXCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/iRU/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1182 (message)"
      - "C:/Users/iRU/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:247 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Users/iRU/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        main.c
        Примечание: включение файла:  C:\\Users\\iRU\\Documents\\GitHub\\YADRO-task\\cmake-build-debug-visual-studio\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Примечание: включение файла:  "
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/iRU/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Users/iRU/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/iRU/Documents/GitHub/YADRO-task/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-kz5236"
      binary: "C:/Users/iRU/Documents/GitHub/YADRO-task/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-kz5236"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      VCPKG_APPLOCAL_DEPS: "ON"
      VCPKG_TARGET_TRIPLET: "x64-windows"
      Z_VCPKG_ROOT_DIR: "C:/Users/iRU/.vcpkg-clion/vcpkg"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/iRU/Documents/GitHub/YADRO-task/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-kz5236'
        
        Run Build Command(s): C:/Users/iRU/AppData/Local/Programs/CLion/bin/cmake/win/x64/bin/cmake.exe -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_92ac5\\fast
        	"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX64\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_92ac5.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_92ac5.dir\\build
        Building C object CMakeFiles/cmTC_92ac5.dir/CMakeCCompilerABI.c.obj
        	C:\\Users\\iRU\\AppData\\Local\\Programs\\CLion\\bin\\cmake\\win\\x64\\bin\\cmake.exe -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_92ac5.dir\\CMakeCCompilerABI.c.obj.d --working-dir=C:\\Users\\iRU\\Documents\\GitHub\\YADRO-task\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-kz5236 --filter-prefix="╧Ёшьхўрэшх: тъы■ўхэшх Їрщыр:  " -- C:\\PROGRA~2\\MICROS~3\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1427~1.291\\bin\\Hostx64\\x64\\cl.exe @C:\\Users\\iRU\\AppData\\Local\\Temp\\nm726B.tmp
        CMakeCCompilerABI.c
        Linking C executable cmTC_92ac5.exe
        	C:\\Users\\iRU\\AppData\\Local\\Programs\\CLion\\bin\\cmake\\win\\x64\\bin\\cmake.exe -E vs_link_exe --intdir=CMakeFiles\\cmTC_92ac5.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100183~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100183~1.0\\x64\\mt.exe --manifests -- C:\\PROGRA~2\\MICROS~3\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1427~1.291\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_92ac5.dir\\objects1.rsp @C:\\Users\\iRU\\AppData\\Local\\Temp\\nm73D3.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_92ac5.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_92ac5.dir/embed.manifest
        RC Pass 1:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100183~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_92ac5.dir/manifest.res CMakeFiles\\cmTC_92ac5.dir/manifest.rc
        LINK Pass 1:
        C:\\PROGRA~2\\MICROS~3\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1427~1.291\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_92ac5.dir\\objects1.rsp /out:cmTC_92ac5.exe /implib:cmTC_92ac5.lib /pdb:C:\\Users\\iRU\\Documents\\GitHub\\YADRO-task\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-kz5236\\cmTC_92ac5.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_92ac5.dir/intermediate.manifest CMakeFiles\\cmTC_92ac5.dir/manifest.res
        MT:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100183~1.0\\x64\\mt.exe /nologo /manifest CMakeFiles\\cmTC_92ac5.dir/intermediate.manifest /out:CMakeFiles\\cmTC_92ac5.dir/embed.manifest /notify_update
        RC Pass 2:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100183~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_92ac5.dir/manifest.res CMakeFiles\\cmTC_92ac5.dir/manifest.rc
        FINAL LINK:
        C:\\PROGRA~2\\MICROS~3\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1427~1.291\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_92ac5.dir\\objects1.rsp /out:cmTC_92ac5.exe /implib:cmTC_92ac5.lib /pdb:C:\\Users\\iRU\\Documents\\GitHub\\YADRO-task\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-kz5236\\cmTC_92ac5.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_92ac5.dir/intermediate.manifest CMakeFiles\\cmTC_92ac5.dir/manifest.res
        	C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -noprofile -executionpolicy Bypass -file C:/Users/iRU/.vcpkg-clion/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/Users/iRU/Documents/GitHub/YADRO-task/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-kz5236/cmTC_92ac5.exe -installedDir C:/Users/iRU/.vcpkg-clion/vcpkg/installed/x64-windows/debug/bin -OutVariable out
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/iRU/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Users/iRU/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/iRU/Documents/GitHub/YADRO-task/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-ehlzx2"
      binary: "C:/Users/iRU/Documents/GitHub/YADRO-task/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-ehlzx2"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      VCPKG_APPLOCAL_DEPS: "ON"
      VCPKG_TARGET_TRIPLET: "x64-windows"
      Z_VCPKG_ROOT_DIR: "C:/Users/iRU/.vcpkg-clion/vcpkg"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/iRU/Documents/GitHub/YADRO-task/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-ehlzx2'
        
        Run Build Command(s): C:/Users/iRU/AppData/Local/Programs/CLion/bin/cmake/win/x64/bin/cmake.exe -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_4b681\\fast
        	"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX64\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_4b681.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_4b681.dir\\build
        Building CXX object CMakeFiles/cmTC_4b681.dir/CMakeCXXCompilerABI.cpp.obj
        	C:\\Users\\iRU\\AppData\\Local\\Programs\\CLion\\bin\\cmake\\win\\x64\\bin\\cmake.exe -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_4b681.dir\\CMakeCXXCompilerABI.cpp.obj.d --working-dir=C:\\Users\\iRU\\Documents\\GitHub\\YADRO-task\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-ehlzx2 --filter-prefix="╧Ёшьхўрэшх: тъы■ўхэшх Їрщыр:  " -- C:\\PROGRA~2\\MICROS~3\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1427~1.291\\bin\\Hostx64\\x64\\cl.exe @C:\\Users\\iRU\\AppData\\Local\\Temp\\nm779B.tmp
        CMakeCXXCompilerABI.cpp
        Linking CXX executable cmTC_4b681.exe
        	C:\\Users\\iRU\\AppData\\Local\\Programs\\CLion\\bin\\cmake\\win\\x64\\bin\\cmake.exe -E vs_link_exe --intdir=CMakeFiles\\cmTC_4b681.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100183~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100183~1.0\\x64\\mt.exe --manifests -- C:\\PROGRA~2\\MICROS~3\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1427~1.291\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_4b681.dir\\objects1.rsp @C:\\Users\\iRU\\AppData\\Local\\Temp\\nm7809.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_4b681.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_4b681.dir/embed.manifest
        RC Pass 1:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100183~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_4b681.dir/manifest.res CMakeFiles\\cmTC_4b681.dir/manifest.rc
        LINK Pass 1:
        C:\\PROGRA~2\\MICROS~3\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1427~1.291\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_4b681.dir\\objects1.rsp /out:cmTC_4b681.exe /implib:cmTC_4b681.lib /pdb:C:\\Users\\iRU\\Documents\\GitHub\\YADRO-task\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-ehlzx2\\cmTC_4b681.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_4b681.dir/intermediate.manifest CMakeFiles\\cmTC_4b681.dir/manifest.res
        MT:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100183~1.0\\x64\\mt.exe /nologo /manifest CMakeFiles\\cmTC_4b681.dir/intermediate.manifest /out:CMakeFiles\\cmTC_4b681.dir/embed.manifest /notify_update
        RC Pass 2:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100183~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_4b681.dir/manifest.res CMakeFiles\\cmTC_4b681.dir/manifest.rc
        FINAL LINK:
        C:\\PROGRA~2\\MICROS~3\\2019\\COMMUN~1\\VC\\Tools\\MSVC\\1427~1.291\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_4b681.dir\\objects1.rsp /out:cmTC_4b681.exe /implib:cmTC_4b681.lib /pdb:C:\\Users\\iRU\\Documents\\GitHub\\YADRO-task\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-ehlzx2\\cmTC_4b681.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_4b681.dir/intermediate.manifest CMakeFiles\\cmTC_4b681.dir/manifest.res
        	C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -noprofile -executionpolicy Bypass -file C:/Users/iRU/.vcpkg-clion/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/Users/iRU/Documents/GitHub/YADRO-task/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-ehlzx2/cmTC_4b681.exe -installedDir C:/Users/iRU/.vcpkg-clion/vcpkg/installed/x64-windows/debug/bin -OutVariable out
        
      exitCode: 0
...
